/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verificar estado del servicio
         * @description Retorna el estado de salud del backend y sus dependencias (LLM, OCI).
         */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/triage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Procesar y clasificar documento clínico
         * @description Endpoint principal del agente. Recibe un documento clínico en cualquier
         *     formato soportado, ejecuta el grafo LangGraph de decisión y retorna el
         *     resultado de triaje con clasificación, entidades extraídas y decisión
         *     de enrutamiento.
         *
         *     ### Casos de prueba obligatorios
         *     1. **Rutina**: score_confianza ≥ 0.8 + nivel no urgente → `Cola_Rutina`
         *     2. **Urgente**: score_confianza ≥ 0.8 + hallazgo crítico → `Cola_Emergencia_Medica`
         *     3. **Ambiguo**: score_confianza < 0.5 → `Cola_Auditoria_Humana`
         */
        post: operations["procesarDocumentoClinico"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/triage/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cargar y procesar un archivo clínico
         * @description Cargar y procesar un archivo clínico.
         */
        post: operations["subirDocumentoClinico"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar documentos procesados
         * @description Retorna la lista de documentos procesados, filtrables por estado y prioridad.
         */
        get: operations["listarDocumentos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{documento_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener documento procesado por ID
         * @description Retorna el resultado de triaje de un documento específico según su identificador único.
         */
        get: operations["obtenerDocumentoPorId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Registrar decisión de auditoría humana (HITL)
         * @description Permite a un auditor clínico aprobar, rechazar o reclasificar
         *     un documento derivado a auditoría humana.
         */
        patch: operations["registrarDecisionAuditoria"];
        trace?: never;
    };
    "/documents/{documento_id}/historial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar trazabilidad funcional del documento
         * @description Consultar trazabilidad funcional del documento.
         */
        get: operations["obtenerHistorialDocumento"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar sesión
         * @description Iniciar sesión.
         */
        post: operations["iniciarSesion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cerrar sesión
         * @description Cerrar sesión.
         */
        post: operations["cerrarSesion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar usuario autenticado
         * @description Consultar usuario autenticado.
         */
        get: operations["consultarSesion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar usuarios
         * @description Listar usuarios.
         */
        get: operations["listarUsuarios"];
        put?: never;
        /**
         * Registrar usuario
         * @description Registrar usuario.
         */
        post: operations["registrarUsuario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Actualizar usuario, rol o estado
         * @description Actualizar usuario, rol o estado.
         */
        put: operations["actualizarUsuario"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar y listar pacientes
         * @description Buscar y listar pacientes.
         */
        get: operations["listarPacientes"];
        put?: never;
        /**
         * Registrar paciente
         * @description Registrar paciente.
         */
        post: operations["registrarPaciente"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/unlinked-documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar documentos sin paciente asociado
         * @description Listar documentos sin paciente asociado.
         */
        get: operations["listarDocumentosSinPaciente"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener paciente
         * @description Obtener paciente.
         */
        get: operations["obtenerPaciente"];
        /**
         * Actualizar paciente
         * @description Actualizar paciente.
         */
        put: operations["actualizarPaciente"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar historial documental del paciente
         * @description Consultar historial documental del paciente.
         */
        get: operations["listarDocumentosPaciente"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{id}/documents/{documento_id}/associate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Asociar un documento a un paciente
         * @description Asociar un documento a un paciente.
         */
        post: operations["asociarDocumentoPaciente"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener configuración del sistema
         * @description Obtener configuración del sistema.
         */
        get: operations["obtenerConfiguracion"];
        put?: never;
        /**
         * Actualizar modo de almacenamiento
         * @description Actualizar modo de almacenamiento.
         */
        post: operations["actualizarConfiguracion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Documento de entrada al triaje. canal_origen conserva el valor vacío por defecto de la API. */
        DocumentoClinico: {
            /**
             * @description Identificador único del documento
             * @example DOC-CLIN-2026-8942
             */
            documento_id: string;
            /**
             * @example PDF
             * @enum {string}
             */
            tipo_archivo: "PDF" | "IMAGEN" | "TEXTO" | "JSON";
            /**
             * @description Contenido en texto plano (si ya está extraído)
             * @example HOSPITAL SANTA LUCIA - INFORME DE ESTUDIO RADIOLOGICO...
             */
            documento_texto?: string | null;
            /** @description Contenido del archivo en base64 (para PDF/imagen) */
            documento_base64?: string | null;
            /**
             * @description Sistema o canal que originó el documento
             * @default
             * @example Guardia_Emergencias
             */
            canal_origen?: string;
            /** @description Metadatos adicionales del documento */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** @description Tipo de documento, prioridad y confianza de la clasificación. */
        Clasificacion: {
            /**
             * @description Catálogo clínico más los valores de compatibilidad que devuelve actualmente la API: Desconocido (sin texto), Error (fallo de clasificación) y Documento Clínico (registro histórico sin tipo). No admite texto arbitrario.
             * @example Informe de Estudio por Imágenes
             * @enum {string}
             */
            tipo_documento: "Informe Clínico" | "Evolución Clínica" | "Epicrisis" | "Receta Médica" | "Orden Médica" | "Orden de Procedimiento" | "Solicitud de Interconsulta" | "Informe de Laboratorio" | "Informe de Estudio por Imágenes" | "Informe Quirúrgico" | "Consentimiento Informado" | "Certificado Médico" | "Referencia y Contrarreferencia" | "Registro de Vacunación" | "Otro" | "Desconocido" | "Error" | "Documento Clínico";
            /** @example Radiologia / Neumonologia */
            especialidad?: string | null;
            nivel_prioridad: components["schemas"]["PrioridadTriaje"];
            /**
             * Format: float
             * @example 0.99
             */
            score_confianza_clasificacion: number;
        };
        /** @description Identificación del paciente extraída del documento. */
        Paciente: {
            /** @example Carlos Eduardo Mendes */
            nombre?: string | null;
            /** @example 52 */
            edad?: number | null;
            id_paciente?: string | null;
            documento_identidad?: string | null;
            historia_clinica?: string | null;
        };
        /** @description Identificación del médico que solicita la atención. */
        MedicoSolicitante: {
            /** @example Dra. Renata Silveira */
            nombre?: string | null;
            /** @example 145892 */
            matricula?: string | null;
        };
        /** @description Datos clínicos que actualmente extrae el agente. */
        DatosExtraidos: {
            paciente?: components["schemas"]["Paciente"] | null;
            medico_solicitante?: components["schemas"]["MedicoSolicitante"] | null;
            /** @example Tomografia de Torax con contraste */
            estudio_realizado?: string | null;
            /** @example Tromboembolismo Pulmonar Agudo (TEP) */
            diagnostico_principal?: string | null;
            /** @example I26.9 */
            cie10_sugerido?: string | null;
            /**
             * @description Descripción nosológica del catálogo CIE-10 versionado, separada del diagnóstico original.
             * @example Embolia pulmonar sin mención de corazón pulmonar agudo
             */
            cie10_descripcion?: string | null;
            hallazgos_clave?: string[] | null;
        };
        /** @description Mensaje emitido para comunicar una urgencia. */
        Notificacion: {
            /** @example Alerta_Guardia_Medica */
            canal: string;
            /** @example ALERTA URGENTE: Informe crítico de TEP Agudo... */
            mensaje: string;
        };
        /** @description Destino del documento y justificación de la revisión humana. */
        DecisionEnrutamiento: {
            /**
             * @example Cola_Emergencia_Medica
             * @enum {string}
             */
            destino_principal: "Cola_Emergencia_Medica" | "Cola_Rutina" | "Farmacia_Hospitalaria" | "Cola_Auditoria_Humana" | "Cola_Revision_Ambigua";
            /** @example false */
            requiere_auditoria_humana: boolean;
            /** @example Hallazgo crítico de alta gravedad detectado. */
            justificacion_enrutamiento: string;
            notificacion_generada?: components["schemas"]["Notificacion"] | null;
        };
        /** @description Rutas del archivo y resultado, tanto en almacenamiento local como OCI. */
        AlmacenamientoOCI: {
            /** @example mediflow-documentos-clinicos */
            bucket?: string | null;
            /** @example urgentes/DOC-CLIN-2026-8942/resultado.json */
            ruta_objeto?: string | null;
            archivo_original?: string | null;
            resultado_json?: string | null;
            nombre_original?: string | null;
            /**
             * @example exito
             * @enum {string}
             */
            status_backup?: "exito" | "error" | "pendiente";
        };
        /** @description Resultado del procesamiento clínico y su decisión de enrutamiento. */
        ResultadoTriaje: {
            /**
             * @example procesado
             * @enum {string}
             */
            status: "recibido" | "procesando" | "procesado" | "pendiente_auditoria" | "rechazado" | "no_soportado" | "error";
            /** @example DOC-CLIN-2026-8942 */
            documento_id: string;
            clasificacion: components["schemas"]["Clasificacion"];
            datos_extraidos: components["schemas"]["DatosExtraidos"];
            decision_enrutamiento: components["schemas"]["DecisionEnrutamiento"];
            almacenamiento_oci?: components["schemas"]["AlmacenamientoOCI"] | null;
            /** @example 1240 */
            tiempo_procesamiento_ms?: number | null;
            /** @description Fecha de registro disponible al consultar documentos persistidos. */
            created_at?: string | null;
        };
        /** @description Decisión humana y correcciones sobre un documento auditado. */
        DecisionAuditoria: {
            /** @enum {string} */
            decision: "aprobar" | "rechazar" | "reclasificar";
            nueva_clasificacion?: {
                [key: string]: unknown;
            } | null;
            datos_corregidos?: {
                [key: string]: unknown;
            } | null;
            comentario?: string | null;
        };
        /** @description Modelo de entidades clínicas estructuradas reservado para consumidores del contrato. El flujo actual devuelve DatosExtraidos; no implica nuevas capacidades del agente. */
        EntidadesMedicas: {
            /** @description Lista de diagnósticos identificados en el documento */
            diagnosticos?: components["schemas"]["DiagnosticoEntidad"][] | null;
            /** @description Procedimientos o estudios médicos mencionados */
            procedimientos?: components["schemas"]["ProcedimientoEntidad"][] | null;
            /** @description Medicamentos mencionados con dosis y frecuencia cuando están disponibles */
            medicamentos?: components["schemas"]["MedicamentoEntidad"][] | null;
            /** @description Hallazgos marcados como críticos o urgentes por el agente */
            hallazgos_criticos?: string[] | null;
            /**
             * Format: float
             * @description Puntuación de confianza del proceso de extracción de entidades
             * @example 0.87
             */
            score_ner?: number | null;
        };
        /**
         * @description Nivel de prioridad clínica asignado por el agente de triaje.
         *     - **Urgente**: requiere atención inmediata o enrutamiento a emergencias.
         *     - **Rutina**: flujo normal de procesamiento médico.
         *     - **Ambiguo**: documento ilegible o con baja confianza; deriva a auditoría humana (HITL).
         * @example Urgente
         * @enum {string}
         */
        PrioridadTriaje: "Urgente" | "Rutina" | "Ambiguo";
        /** @description Error HTTP vigente de FastAPI. detail puede ser texto o el detalle estructurado de MediFlow. */
        ErrorResponse: {
            detail: string | components["schemas"]["DetalleError"];
        };
        /** @description Disponibilidad del servicio y de sus dependencias. */
        HealthResponse: {
            /**
             * @example ok
             * @enum {string}
             */
            status: "ok" | "unavailable";
            /** @example 1.0.0 */
            version: string;
            /** @example true */
            postgres_disponible: boolean;
            /** @example true */
            llm_disponible?: boolean;
            /** @example true */
            oci_disponible?: boolean;
        };
        /** @description Datos públicos de un usuario del sistema. */
        Usuario: {
            /** Format: uuid */
            id: string;
            documento_identidad: string;
            nombres: string;
            apellidos: string;
            correo?: string | null;
            telefono?: string | null;
            /** @enum {string} */
            rol: "ADMINISTRADOR" | "OPERADOR" | "AUDITOR" | "SUPERVISOR";
            /** @enum {string} */
            estado: "ACTIVO" | "INACTIVO";
            created_at?: string | null;
        };
        /** @description Datos necesarios para registrar un usuario. */
        UsuarioCrear: {
            documento_identidad: string;
            /** Format: password */
            password: string;
            nombres: string;
            apellidos: string;
            correo?: string | null;
            telefono?: string | null;
            /**
             * @default OPERADOR
             * @enum {string}
             */
            rol?: "ADMINISTRADOR" | "OPERADOR" | "AUDITOR" | "SUPERVISOR";
            /**
             * @default ACTIVO
             * @enum {string}
             */
            estado?: "ACTIVO" | "INACTIVO";
        };
        /** @description Configuración vigente; el modo de almacenamiento se cambia manualmente. */
        ConfiguracionSistema: {
            /** @enum {string} */
            storage_mode: "LOCAL" | "OCI";
            oci_configured: boolean;
            llm_provider: string;
            llm_configured: boolean;
            database_url_configured: boolean;
        };
        /** @description Datos de registro de un paciente. */
        PacienteRegistrar: {
            /** @enum {string} */
            tipo_documento: "DNI" | "CE" | "PASAPORTE";
            numero_documento: string;
            historia_clinica?: string | null;
            nombres: string;
            apellidos: string;
            /** Format: date */
            fecha_nacimiento?: string | null;
            /** @enum {string|null} */
            sexo?: "M" | "F" | "OTRO" | null;
            telefono?: string | null;
            correo?: string | null;
        };
        /** @description Paciente registrado con su identificador. */
        PacienteRegistrado: components["schemas"]["PacienteRegistrar"] & {
            /** Format: uuid */
            id: string;
            nombre_completo: string;
            created_at?: string | null;
        };
        /** @description Diagnóstico identificado y código CIE-10 sugerido. */
        DiagnosticoEntidad: {
            /** @example Tromboembolismo Pulmonar Agudo */
            texto: string;
            /** @example I26.9 */
            cie10?: string | null;
            /** @default false */
            es_principal?: boolean;
        };
        /** @description Procedimiento médico mencionado en un documento. */
        ProcedimientoEntidad: {
            /** @example Tomografía de Tórax con contraste */
            texto: string;
            codigo?: string | null;
        };
        /** @description Medicamento mencionado, dosis y frecuencia disponibles. */
        MedicamentoEntidad: {
            /** @example Heparina */
            nombre: string;
            /** @example 80 UI/kg */
            dosis?: string | null;
            /** @example Infusión IV continua */
            frecuencia?: string | null;
        };
        /** @description Cantidad e items retornados por la consulta de documentos. */
        ListaDocumentosResponse: {
            total: number;
            items: components["schemas"]["ResultadoTriaje"][];
        };
        /** @description Código y descripción opcional de un error de MediFlow. */
        DetalleError: {
            error: string;
            mensaje?: string;
            detalle?: string | null;
        };
        /** @description Ubicación y causa de un error de validación de FastAPI. */
        ValidationError: {
            loc: (string | number)[];
            msg: string;
            type: string;
            input?: unknown;
            ctx?: {
                [key: string]: unknown;
            };
        };
        /** @description Respuesta 422 para campos inválidos o ausentes. */
        HTTPValidationError: {
            detail: components["schemas"]["ValidationError"][];
        };
    };
    responses: {
        /** @description Documento procesado exitosamente */
        TriageSuccess: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ResultadoTriaje"];
            };
        };
        /** @description Documento derivado a auditoría humana */
        TriagePendingAudit: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ResultadoTriaje"];
            };
        };
        /** @description Solicitud inválida o documento malformado */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Token Bearer ausente, inválido o expirado */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Documento no encontrado */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Error interno del servidor / agente */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Dependencia requerida no disponible (PostgreSQL, almacenamiento o proveedor LLM) */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Datos de solicitud incompletos o inválidos */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["HTTPValidationError"];
            };
        };
    };
    parameters: {
        PatientId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Servicio operativo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "version": "1.0.0",
                     *       "postgres_disponible": true,
                     *       "llm_disponible": true,
                     *       "oci_disponible": true
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Servicio degradado o no disponible */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    procesarDocumentoClinico: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentoClinico"];
            };
        };
        responses: {
            200: components["responses"]["TriageSuccess"];
            207: components["responses"]["TriagePendingAudit"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    subirDocumentoClinico: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    documento_id: string;
                    canal_origen?: string;
                    /**
                     * Format: binary
                     * @description PDF, JPG o PNG de hasta 10 MB; se valida la firma binaria.
                     */
                    archivo: string;
                };
            };
        };
        responses: {
            200: components["responses"]["TriageSuccess"];
            207: components["responses"]["TriagePendingAudit"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description El archivo supera los 10 MB */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description MIME, firma o formato no permitido */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listarDocumentos: {
        parameters: {
            query?: {
                estado?: "procesado" | "pendiente_auditoria" | "error";
                nivel_prioridad?: components["schemas"]["PrioridadTriaje"];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de resultados de triaje */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaDocumentosResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Rol sin permisos de auditoría */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    obtenerDocumentoPorId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example DOC-CLIN-2026-8942 */
                documento_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resultado de triaje del documento */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoTriaje"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    registrarDecisionAuditoria: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionAuditoria"];
            };
        };
        responses: {
            /** @description Decisión de auditoría registrada correctamente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoTriaje"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Rol sin permisos de auditoría */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description El documento ya no está pendiente de auditoría humana */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Datos de auditoría inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    obtenerHistorialDocumento: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Secuencia cronológica de eventos del documento */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        documento_id: string;
                        items: {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    iniciarSesion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    documento_identidad: string;
                    /** Format: password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Sesión iniciada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        access_token: string;
                        /** @example Bearer */
                        token_type: string;
                        user: components["schemas"]["Usuario"];
                        mensaje: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Usuario inactivo */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description PostgreSQL no disponible para crear la sesión */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cerrarSesion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesión invalidada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description PostgreSQL no disponible para revocar la sesión */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    consultarSesion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuario de la sesión */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Usuario"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description PostgreSQL no disponible para validar la sesión */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listarUsuarios: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuarios registrados */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Usuario"][];
                };
            };
            /** @description Requiere rol ADMINISTRADOR */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    registrarUsuario: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsuarioCrear"];
            };
        };
        responses: {
            /** @description Usuario registrado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Usuario"];
                };
            };
            /** @description Usuario duplicado o datos inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Requiere rol ADMINISTRADOR */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    actualizarUsuario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    nombres?: string;
                    apellidos?: string;
                    correo?: string | null;
                    telefono?: string | null;
                    /** @enum {string} */
                    rol?: "ADMINISTRADOR" | "OPERADOR" | "AUDITOR" | "SUPERVISOR";
                    /** @enum {string} */
                    estado?: "ACTIVO" | "INACTIVO";
                    /** Format: password */
                    password?: string;
                };
            };
        };
        responses: {
            /** @description Usuario actualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Usuario"];
                };
            };
            /** @description Usuario no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listarPacientes: {
        parameters: {
            query?: {
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pacientes encontrados */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        total?: number;
                        items?: components["schemas"]["PacienteRegistrado"][];
                    };
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    registrarPaciente: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PacienteRegistrar"];
            };
        };
        responses: {
            /** @description Paciente registrado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Documento o historia clínica duplicados */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listarDocumentosSinPaciente: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Documentos disponibles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    obtenerPaciente: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PatientId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paciente encontrado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PacienteRegistrado"];
                };
            };
            /** @description Paciente no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    actualizarPaciente: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PatientId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Paciente actualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Paciente no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listarDocumentosPaciente: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PatientId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Historial clínico documental */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Paciente no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    asociarDocumentoPaciente: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PatientId"];
                documento_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Documento asociado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Paciente o documento no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    obtenerConfiguracion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configuración activa */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfiguracionSistema"];
                };
            };
            /** @description Requiere rol ADMINISTRADOR */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    actualizarConfiguracion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    storage_mode: "LOCAL" | "OCI";
                };
            };
        };
        responses: {
            /** @description Configuración actualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfiguracionSistema"];
                };
            };
            /** @description OCI seleccionado sin credenciales completas */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Requiere rol ADMINISTRADOR */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
}
